export * as Arrow1 from './images/arrow1.svg';
export * as Arrow2 from './images/arrow2.svg';
export * as BannerBg from './images/banner-bg.png';
export * as ColorSharp from './images/color-sharp.png';
export * as ContactImg from './images/contact.svg';
export * as Header from './images/header-img.svg';
export * as Logo from './images/logo.svg';
export * as Footer from './images/footer-bg.png';
export * as Profile from './images/profile.png';
